# SPDX-FileCopyrightText: 2022 Jukereise
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Moony
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Sissel
# SPDX-FileCopyrightText: 2022 Veritius
# SPDX-FileCopyrightText: 2023 Checkraze
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 Emisse
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2023 Kesiath
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 coolmankid12345
# SPDX-FileCopyrightText: 2023 freeman2651
# SPDX-FileCopyrightText: 2023 ninruB
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 ErhardSteinhauer
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Nairod
# SPDX-FileCopyrightText: 2024 PopGamer46
# SPDX-FileCopyrightText: 2024 PotentiallyTom
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2025 Daniel Lenrd
# SPDX-FileCopyrightText: 2025 core-mene
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadetOld
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 #15 hrs
      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  ## Frontier: commented out stuff below
  # access:
  # - Security
  # - Brig
  # - Maintenance
  # - Service
  # - External
  # - Cryogenics
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  ## End Frontier: commented out stuff above
  setPreference: false # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: SecurityCadetGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: BookSecurity
  storage:
    back:
    - Flash
    - Magazine45_ACPPistolFMJ
