# SPDX-FileCopyrightText: 2021 Alex Evgrashin
# SPDX-FileCopyrightText: 2021 Leon Friedrich
# SPDX-FileCopyrightText: 2021 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2022 Fishfish458
# SPDX-FileCopyrightText: 2022 Flipp Syder
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Kevin Zheng
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 ZeroDayDaemon
# SPDX-FileCopyrightText: 2022 Zymem
# SPDX-FileCopyrightText: 2022 fishfish458 <fishfish458>
# SPDX-FileCopyrightText: 2022 mirrorcult
# SPDX-FileCopyrightText: 2022 theashtronaut
# SPDX-FileCopyrightText: 2023 Alekshhh
# SPDX-FileCopyrightText: 2023 Checkraze
# SPDX-FileCopyrightText: 2023 DerbyX
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2023 Jackal298
# SPDX-FileCopyrightText: 2023 Lei Yunxing
# SPDX-FileCopyrightText: 2023 Puro
# SPDX-FileCopyrightText: 2023 Topy
# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2023 lapatison
# SPDX-FileCopyrightText: 2023 metalgearsloth
# SPDX-FileCopyrightText: 2023 nikthechampiongr
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 Hanz
# SPDX-FileCopyrightText: 2024 Ubaser
# SPDX-FileCopyrightText: 2024 lzk
# SPDX-FileCopyrightText: 2024 Джексон Миссиссиппи
# SPDX-FileCopyrightText: 2025 Coenx-flex
# SPDX-FileCopyrightText: 2025 Killerqu00
# SPDX-FileCopyrightText: 2025 Whatstone
# SPDX-FileCopyrightText: 2025 core-mene
# SPDX-FileCopyrightText: 2025 pathetic meowmeow
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: LockerBoozeFilled
  suffix: Filled
  parent: LockerBooze
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorBasicSlim
#      - id: WeaponShotgunDoubleBarreledRubber # Frontier
      - id: DrinkShaker
      - id: ClothingEyesHudBeer
      - id: HandLabeler
        amount: 1
      - id: DrinkBottleBeer
        prob: 0.5
      - id: DrinkBottleBeer
        prob: 0.5
      - id: DrinkBottleBeer
        prob: 0.5
#      - id: AmmoBox12_gaugeBeanbag # Frontier
#        amount: 2  # Frontier
      - id: RagItem
        amount: 2

#- type: entity
#  id: LockerFormalFilled
#  suffix: Filled
#  parent: LockerFormal

- type: entity
  id: ClosetChefFilled
  suffix: Filled
  parent: ClosetChef
  components:
  - type: StorageFill
    contents:
      - id: CrowbarRed
      - id: VariantCubeBox
      - id: BoxMousetrap
        amount: 2
      - id: SprayBottleWater
      - id: ReagentContainerFlour
        amount: 2
      # - id: FoodBoxCloth # Frontier
      #   amount: 1 # Frontier
      - id: ReagentContainerSugar
      - id: FoodCondimentPacketSalt
        amount: 3
      - id: FoodCondimentPacketPepper
        amount: 3
      - id: FoodCondimentBottleEnzyme
      # really, milk should go in the fridge. Unfortunately saltern only has freezers.
      # yes, I'm using this as an excuse to not have to do extra work.
      - id: DrinkMilkCarton
        amount: 2
      - id: DrinkSoyMilkCarton

- type: entity
  id: ClosetJanitorFilled
  suffix: Filled
  parent: ClosetJanitor
  components:
  - type: StorageFill
    contents:
      - id: MopItem
        amount: 2
      - id: BoxMousetrap
        amount: 2
      - id: WetFloorSign
        amount: 3
      - id: TrashBag
        amount: 2
      - id: LightReplacer
      - id: BoxLightMixed
      - id: Holoprojector
      - id: SoapNT
        amount: 2
      - id: FlashlightLantern
        amount: 2
      - id: Plunger
        amount: 2

- type: entity
  id: ClosetLegalFilled
  suffix: Filled
  parent: ClosetLegal
  components:
  - type: StorageFill
    contents:
      - id: BriefcaseBrownFilled
      - id: ClothingOuterRobesJudge

- type: entity
  id: LockerBotanistFilled
  suffix: Filled
  parent: LockerBotanist
  components:
  - type: StorageFill
    contents:
#      - id: ClothingHandsGlovesLeather # Frontier
#      - id: ClothingOuterApronBotanist # Frontier
#      - id: ClothingHeadBandBotany # Frontier
#      - id: HydroponicsToolClippers # Frontier
#      - id: HydroponicsToolSpade # Frontier
#      - id: HydroponicsToolMiniHoe # Frontier
#      - id: RobustHarvestChemistryBottle # Frontier
#      - id: ClothingBeltPlant # Frontier
      - id: ClothingBeltPlantFilled # Frontier
      - id: PlantBag ##Some maps don't have nutrivend
      - id: BoxMouthSwab
      - id: Dropper
#      - id: HandLabeler
#      - id: ClothingUniformOveralls # Frontier
#      - id: ClothingHeadHatTrucker # Frontier
#        prob: 0.1

- type: entity
  id: LockerBotanistLoot
  suffix: Loot
  parent: LockerBotanist
  components:
  - type: StorageFill
    contents:
      - id: ClothingUniformOveralls
      - id: ClothingHeadHatTrucker
        prob: 0.3
      - id: GatfruitSeeds
        prob: 0.1
      - id: FlyAmanitaSeeds
        prob: 0.5
      - id: NettleSeeds
        prob: 0.7

- type: entity
  id: ClosetJanitorBombFilled
  parent: ClosetJanitorBomb
  suffix: DO NOT MAP, Filled
  # categories: [ DoNotMap ] Mono
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetJanitorBombSuit
      - id: ClothingOuterSuitJanitorBomb
